

<?php 
#get a list of the manufacturers;

//get the category id 
//$category_id = $this->getRequest()->getParam('category');
$category_id =$this->getCategoryname();


//echo "the cat is num is ".$category_id;

switch($category_id){
	case "Casting Rods":
		//casting rods cat 18
		$manufacturer_ids = array("shimano","okuma","impulse","castaway","abu garcia","13 fishing","Quantum","dobyns","lews","daiwa","G Loomis","falcon","kistler","g rods","ardent","power tackle");
		$cat_id = 18;
		break; 

	case "Casting Reels":
		//casting reels cat 19
		$manufacturer_ids = array("abu garcia","shimano","daiwa","okuma","13 fishing","ardent","lews","quantum","duckett","zebco");
		$cat_id = 19;
		break; 
	case "Spinning Reels":
		//Spinning Reels cat 89
		$manufacturer_ids = array("abu garcia","shimano","daiwa","okuma","13 fishing","ardent","lews","quantum","duckett","zebco");

		$cat_id = 89; 
		break;

	case "Spinning Rods":
		//spinning Rods cat 90

		$manufacturer_ids = array("shimano","okuma","impulse","castaway","abu garcia","13 fishing","Quantum","dobyns","lews","daiwa","G Loomis","falcon","kistler","g rods","ardent","power tackle");
		$cat_id = 90; 
		break;

	default:
		$manufacturer_ids = array("shimano","okuma","impulse","castaway","abu garcia","13 fishing","Quantum","dobyns","lews","daiwa","G Loomis","falcon","kistler","g rods","ardent","power tackle");
		$cat_id = 18; 
	break;

}





 $name='manufacturer';
    $attributeInfo = Mage::getResourceModel('eav/entity_attribute_collection')->setCodeFilter($name)->getFirstItem();
    $attributeId = $attributeInfo->getAttributeId();
    $attribute = Mage::getModel('catalog/resource_eav_attribute')->load($attributeId);
    $attributeOptions = $attribute ->getSource()->getAllOptions(false); 
    //print_r($attributeOptions);

    foreach($attributeOptions as $attribute){
    	foreach($manufacturer_ids as $id){
    		if($id==$attribute['label']){
    			$attarrs[]= $attribute['label'].".jpg";
    		}
    	}
    }

    sort($attarrs);

    /*foreach($attarrs as $att=>$val){
    	echo $val."<br />";
    }*/

?>


<div class="page-title category-title">
        <h1><?php echo ucwords($category_id); ?></h1>
</div>
<div class="category-list-wrapper">
<div class="category-products shopbybrandcategory-class">
	<ul class="products-grid">
		<?php
			

			$categorycount = 0;
		foreach ($attarrs as $att=>$image):
			

			
			$filepath =  str_replace(' ','%20',Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'brands'.DS.$image);
			
			$url = getimagesize($filepath);


			if(is_array($url)){
				$immagine = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'brands'.DS.$image;
			}else{
				$immagine = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."brands".DS."image.jpg";
			}

			if ($categorycount == 0){
				$class = "first";
			}elseif ($categorycount == 3){
				$class = "last";
			}else{
				$class = "";
			}
			?>
			<div class="catalog-image">

			<div>
				<?php $params = Mage::getUrl('shopbybrandcategory/brand', array('manufacturer'=>str_replace('.jpg', '', $image),'category'=>$cat_id,'p'=>1,'limit'=>20)); ?>

			<a href="<?php echo $params ?>">
			<img src="<?php echo $immagine ?>" alt="#" width="390" height="210" />
			</a>
			</div>
				
			<div class="left"><h2><a href="<?php echo $params ?>?p=1&limit=20">
				
				<?php echo ucwords(str_replace('.jpg', '', $image)); ?></a></h2></div>

			</div>
			<?php
			
			if($categorycount == 3){
				$categorycount = 0;
				
			}
			else{
				$categorycount++;
			}
			endforeach;
			
			?>
		</ul>
	</div></div>